baseurl: 'https://dulcet-stardust-5fd858.netlify.app'
theme: "hugo-theme-learn"
baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$

markup:
  goldmark:
    renderer:
      unsafe: true
